export default {
  colors: {
    primary: '#131118',
    secondary: '#f0f0f0',
    warning: '#e11d48',
    success: '#16a34a',
    info: '#3b82f6',
    white: '#ffffff',
    black: '#000000',
    gray: '#c5c5c5',
    background: '#f5f5f5',
    text: '#262626',
  },
  font: {
    family: {
      primary: "'Montserrat', sans-serif",
    },
    sizes: {
      xs: '.8rem',
      sm: '1.2rem',
      md: '1.6rem',
      lg: '2.4rem',
      xl: '3.2rem',
      '2xl': '4rem',
      '3xl': '4.8rem',
      '4xl': '5.6rem',
      '5xl': '6.4rem',
      '6xl': '7.2rem',
      '7xl': '8rem',
    },
  },
  media: {
    lteOrEqSmallest: '(max-width: 320px)',
    lteOrEqSmall: '(max-width: 576px)',
    lteOrEqMedium: '(max-width: 768px)',
    lteOrEqLarge: '(max-width: 992px)',
    lteOrEqXLarge: '(max-width: 1200px)',
    gteOrEqSmallest: '(min-width: 320px)',
    gteOrEqSmall: '(min-width: 576px)',
    gteOrEqMedium: '(min-width: 768px)',
    gteOrEqLarge: '(min-width: 992px)',
    gteOrEqXLarge: '(min-width: 1200px)',
  },
  spacings: {
    xs: '.8rem',
    sm: '1rem',
    md: '1.6rem',
    lg: '2.4rem',
    xl: '3.2rem',
    '2xl': '4rem',
    '3xl': '4.8rem',
    '4xl': '5.6rem',
    '5xl': '6.4rem',
    '6xl': '7.2rem',
    '7xl': '8rem',
  },
  frameSizes: {
    xs: '8rem',
    sm: '12rem',
    md: '24rem',
    lg: '32rem',
    xl: '40rem',
    '2xl': '56rem',
    '3xl': '64rem',
    '4xl': '80rem',
    '5xl': '104rem',
    '6xl': '120rem',
    '7xl': '134rem',
  },
  transitions: {
    fastest: 'all 100ms ease-in-out',
    faster: 'all 150ms ease-in-out',
    fast: 'all 200ms ease-in-out',
    normal: 'all 250ms ease-in-out',
    slow: 'all 300ms ease-in-out',
    slower: 'all 350ms ease-in-out',
    slowest: 'all 400s ease-in-out',
  },
  layers: {
    normal: 0,
    layer1: 1,
    layer2: 2,
    layer3: 3,
    layer4: 4,
    layer5: 5,
    layer6: 6,
    layer7: 7,
    layer8: 8,
    layer9: 9,
    aboveAll: 10,
  },
} as const;
